[package]
name = "py32-metapac-gen"
version = "0.4.1"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
regex = "1.7.1"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "1c198ae678ebd426751513f0deab6fbd6f8b8211" }
serde = { version = "1.0.157", features = [ "derive" ] }
serde_json = "1.0.94"
proc-macro2 = "1.0.52"
py32-data-macros = { version = "0.4.1", path = "../py32-data-macros" }
