[package]
name = "py32-data-serde"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.157", features = ["derive"] }
regex = "1.7.1"
ref_thread_local = "0.1.1"

[dev-dependencies]
itertools = "0.10.5"
rayon = "1.7.0"
serde_json = "1.0.94"
